# Admin

title:            "WILD JOKERS"
author:           "WILD JOKERS"
description:      "WILD JOKERS is a record label that distributes dance music to your face and ear holes. #GetWild"
email:            "wearewildjokers@gmail.com"
tumblr:           "wearewildjokers"
google_analytics: "UA-48339690-1"

# Technical

version:          1.0.0
markdown:         redcarpet
redcarpet:
  extensions:     ["tables"]
highlighter:         true
permalink:        pretty
paginate:         3
paginate_path:    blog/page:num